# This `docker-compose.yaml` is used by the devcontainer to start the development container.
#
# Set following environment variables in your host shell before starting the devcontainer to show
# the raw container build logs in the devcontainer output:
#
# ```
# export COMPOSE_PROGRESS=plain
# export BUILDKIT_PROGRESS=plain
# ```
services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
      pull: true
      args:
        CLAUDE_CONFIG_DIR: ${CLAUDE_CONFIG_DIR}
        CODEX_HOME: ${CODEX_HOME}
        GEMINI_CLI_HOME: ${GEMINI_CLI_HOME}
        GIT_CREDENTIALS_DIR: ${GIT_CREDENTIALS_DIR}
        XDG_DIR: ${XDG_DIR}
        GOPATH_DIR: ${GOPATH_DIR}
        NPM_CONFIG_CACHE_DIR: ${NPM_CONFIG_CACHE_DIR}
    environment:
      BEAR_LOG_DIR: ${BEAR_LOG_DIR}
    volumes:
      # The workspace MUST be mounted to the same as `workspaceFolder` in `devcontainer.json`.
      - ..:/workspace:consistent
      - bear-go-claude-volume:${CLAUDE_CONFIG_DIR}
      - bear-go-codex-volume:${CODEX_HOME}
      - bear-go-gemini-volume:${GEMINI_CLI_HOME}
      - bear-go-git-credentials-volume:${GIT_CREDENTIALS_DIR}
      - bear-go-xdg-volume:${XDG_DIR}
      - bear-go-gopath-volume:${GOPATH_DIR}
      - bear-go-logs-volume:${BEAR_LOG_DIR}
      - bear-go-npm-volume:${NPM_CONFIG_CACHE_DIR}
    command: /bin/sh -c "while sleep 1000; do :; done"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  bear-go-claude-volume:
  bear-go-codex-volume:
  bear-go-gemini-volume:
  bear-go-git-credentials-volume:
  bear-go-xdg-volume:
  bear-go-gopath-volume:
  bear-go-logs-volume:
  bear-go-npm-volume: